// Re-export constants from the new constants file for backward compatibility
import {
  ADVANCED_MAX_DELAY as ADVANCED_MAX_DELAY_CONST,
  ADVANCED_MIN_DELAY as ADVANCED_MIN_DELAY_CONST,
  DIGIT_REGEX as DIGIT_REGEX_CONST,
  LOADING_TEXT as LOADING_TEXT_CONST,
  MAX_DELAY as MAX_DELAY_CONST,
  MIN_DELAY as MIN_DELAY_CONST,
  REVEAL_TEXT as REVEAL_TEXT_CONST,
} from "./phone-protection.constants";

export const LOADING_TEXT = LOADING_TEXT_CONST;
export const REVEAL_TEXT = REVEAL_TEXT_CONST;
export const MIN_DELAY = MIN_DELAY_CONST;
export const MAX_DELAY = MAX_DELAY_CONST;
export const ADVANCED_MIN_DELAY = ADVANCED_MIN_DELAY_CONST;
export const ADVANCED_MAX_DELAY = ADVANCED_MAX_DELAY_CONST;
export const DIGIT_REGEX = DIGIT_REGEX_CONST;
